server:
  servlet:
    context-path: /

  port: 8081
spring:
  application:
    name: accounts-services
  datasource:
    url: "${URL_BD:jdbc:postgresql://localhost:5434/backend_accounts}"
    username: "${USER_NAME_BD:backend_bp_user}"
    password: "${PWD_BD:backend_bp_pass}"
    driverClassName: "org.postgresql.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "none"
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    url: "${URL_BD:jdbc:postgresql://localhost:5434/backend_accounts}"
    user: "${USER_NAME_BD:backend_bp_user}"
    password: "${PWD_BD:backend_bp_pass}"

rest-consumer:
  client-service-base-path: ${CLIENT_SERVICE:http://localhost:8080}
  client-service-get-user-path: ${CLIENT_SERVICE_GET_USER_PATH:/v1/clients/%s}

resilience4j:
  circuitbreaker:
    instances:
      client-service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"